Project/Project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('homepage.urls')),
    url(r'^', include('entries.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^', include('allauth.urls')),
]

Project/entries/urls.py
from django.conf.urls import url

from . import views

app_name = 'entries'

urlpatterns = [
    url(r'^$', views.HomeListView.as_view(), name='home'),
]

Project/homepage/urls.py
from django.conf.urls import url

from . import views

app_name = 'homepage'

urlpatterns = [
    url(r'^$', views.HomeListView.as_view(), name='home'),
]

Project/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'

urlpatterns = [
    url(r'^profile/$', views.ProfileDetailView.as_view(), name='my-profile'),
    url(r'^profile/update/(?P<pk>[0-9]+)$', views.ProfileUpdateView.as_view(), name='profile-update'),
    url(r'^profile/(?P<username>\w+)$', views.ProfileDetailView.as_view(), name='profile'),
]

Project/Project/models.py
from django.db import models

class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-
    . fields.
    updating ``created`` and ``modified``
    """

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

Project/entries/models.py
from django.db import models

# Create your models here.

Project/homepage/models.py
from django.db import models

# Create your models here.

Project/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile')
    website = models.URLField(default='', blank=True)
    bio = models.TextField(default='', blank=True)
    phone = models.CharField(max_length=20, blank=True, default='')

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        user_profile = UserProfile(user=user)
        user_profile.save()

post_save.connect(create_profile, sender=User)

Project/users/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User

from .models import UserProfile

class UserForm(ModelForm):

    class Meta:
        model = User
        fields = ['email']


UserProfilesFormSet = inlineformset_factory(User, UserProfile, fields=('bio', 'phone', 'website'), can_delete=False)

Project/entries/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class HomeListView(TemplateView):
    template_name = 'homepage/home.html'

Project/users/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, UpdateView
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render

from braces.views import LoginRequiredMixin

from django.db import transaction

from .forms import UserProfilesFormSet, UserForm
from .models import UserProfile

# Create your views here.
class ProfileDetailView(DetailView):
    context_object_name = "profile"
    template_name = 'users/profile.html'

    def get_object(self, **kwargs):
        my_username = self.request.user.get_username()
        username = self.kwargs.get('username', my_username)
        return get_object_or_404(UserProfile, user__username=username)

class ProfileUpdateView(UpdateView):

    model = User
    template_name = 'users/profile_update_form.html'
    form_class = UserForm
    success_url = reverse_lazy('homepage:home')


    def get_context_data(self, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['form'] = UserForm(self.request.POST, instance=self.object)
            context['profile_form'] = UserProfilesFormSet(self.request.POST, instance=self.object)
        else:
            context['form'] = UserForm(instance=self.object)
            context['profile_form'] = UserProfilesFormSet(instance=self.object)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        profile_form = UserProfilesFormSet(self.request.POST)
        if (form.is_valid() and profile_form.is_valid()):
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        self.object = form.save()
        profile_form.instance = self.object
        profile_form.save()
        return reverse_lazy('users:my-profile')

    def form_invalid(self, form, profile_form):
        return self.render_to_response(
            self.get_context_data(form=form, profile_form=profile_form))

Project/homepage/templates/homepage/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% load account %}

    {% user_display user as user_display %}
    {% if user_display %}
        logged in as {{ user_display }}<br/>
        <a href="{% url 'users:my-profile' %}">Profile</a><br/>
        <a href="{% url 'account_logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'account_login' %}">Login</a><br/>
        <a href="{% url 'account_signup' %}">Sign-up</a>
    {% endif %}
</body>
</html>

Project/templates/base.html
{% block content %}
{% endblock %}

Project/users/templates/users/profile.html
{% extends 'base.html' %}
{% load account %}


{% block content %}

    <h3>{% user_display user %} Profile</h3>

    Bio: {{ profile.id }}<br/>
    Bio: {{ request.user.id }}<br/>
    <br/>
    Bio: {{ profile.bio }}<br/>
    Website: {{ profile.website }}<br/>
    Email: {{ profile.user.email }}<br/>
    Phone: {{ profile.phone }}<br/>
    <br/>
    <a href="{% url 'users:profile-update' request.user.id %}">Edit</a>



{% endblock %}

Project/users/templates/users/profile_update_form.html
<form role="form" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{ profile_form.as_p }}

    <button type="submit">Submit</button>
</form>